version: '3.8'
services:
  app:
    image: react-developer-portfolio_app:dev
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
