version: '3.8'
services:
  app:
    image: react-developer-portfolio_app:prod
    build:
      context: .
      
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
