# 构建阶段
FROM node:20.5.1 as build-stage

WORKDIR /app

# 更改 npm 的源为淘宝源
RUN npm config set registry https://registry.npm.taobao.org
RUN yarn config set registry https://registry.npm.taobao.org


COPY ../package*.json ./
RUN yarn install

COPY . .
RUN yarn build

# 运行阶段
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

# Nginx 默认配置文件，可能需要根据项目进行调整
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
